---
- name: Set rke2_data_dir
  ansible.builtin.set_fact:
    rke2_data_dir: >-
      {{
        (cluster_rke2_config | from_yaml).get('data-dir') | default(
        (group_rke2_config | from_yaml).get('data-dir')) | default(
        (host_rke2_config | from_yaml).get('data-dir')) | default('/var/lib/rancher/rke2')
      }}
