---
- name: Set rke2_data_dir
  ansible.builtin.set_fact:
    rke2_data_dir: >-
      {{
        host_rke2_config.get('data-dir') | default(
        group_rke2_config.get('data-dir'), boolean=True) | default(
        cluster_rke2_config.get('data-dir'), boolean=True) | default('/var/lib/rancher/rke2', boolean=True)
      }}
