---

- name: CIS MODE
  become: true
  tags: ["cis"]
  when:
    - ((cluster_rke2_config | default({})).profile | default("") | regex_search('^cis(-\\d+.\\d+)?$')) is not none or
      ((group_rke2_config | default({})).profile | default("") | regex_search('^cis(-\\d+.\\d+)?$')) is not none or
      ((host_rke2_config | default({})).profile | default("") | regex_search('^cis(-\\d+.\\d+)?$')) is not none
  block:
    - name: Create etcd group
      ansible.builtin.group:
        name: etcd
        state: present

    - name: Create etcd user
      ansible.builtin.user:
        name: etcd
        comment: etcd user
        shell: /usr/sbin/nologin
        group: etcd
        create_home: false
