---
# =====================================================================
# RKE2 File System Permissions & Hardening (STIG Compliance)
# =====================================================================

# 1. /etc/rancher/rke2 files (root:root, 0600)
- name: Find /etc/rancher/rke2 contents
  ansible.builtin.find:
    paths: "/etc/rancher/rke2"
    file_type: file
  register: found_err_files
  tags: ["stig"]

- name: Find /etc/rancher/rke2 contents
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0600'
  loop: "{{ found_err_files.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  tags: ["stig"]

# 3. /var/lib/rancher/rke2/agent subcomponents (Kubeconfigs, Certs, Keys, Dirs)
- name: Set 0700 on specific agent directories
  ansible.builtin.file:
    path: "{{ rke2_data_dir }}/agent/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0700'
  loop:
    - pod-manifests
    - etc
  failed_when: false
  loop_control:
    label: "{{ item }}"
  tags: ["stig"]

- name: Find agent .kubeconfig files (0640)
  ansible.builtin.find:
    paths: "{{ rke2_data_dir }}/agent"
    patterns: "*.kubeconfig"
    file_type: file
    depth: 1
  register: found_kubeconfigs
  tags: ["stig"]

- name: Secure agent .kubeconfig files (0640)
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0640'
  loop: "{{ found_kubeconfigs.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  tags: ["stig"]

- name: Find agent .crt files (0600)
  ansible.builtin.find:
    paths: "{{ rke2_data_dir }}/agent"
    patterns: "*.crt"
    file_type: file
    depth: 1
  register: found_certs
  tags: ["stig"]

- name: Secure agent .crt files (0600)
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0600'
  loop: "{{ found_certs.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  tags: ["stig"]

- name: Find agent .key files (0600)
  ansible.builtin.find:
    paths: "{{ rke2_data_dir }}/agent"
    patterns: "*.key"
    file_type: file
    depth: 1
  register: found_keys
  tags: ["stig"]

- name: Secure agent .key files (0600)
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0600'
  loop: "{{ found_keys.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  tags: ["stig"]

# 4. Verify correct permissions of the files in /var/lib/rancher/rke2/bin (root:root, 0750)

- name: Find files inside rke2/bin
  ansible.builtin.find:
    paths: "{{ rke2_data_dir }}/bin"
    file_type: file
  register: bin_files
  tags: ["stig"]

- name: Secure files inside rke2/bin
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0750'
  loop: "{{ bin_files.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  tags: ["stig"]

# 5. Verify correct permissions of all directories in /var/lib/rancher/rke2/ (root:root, 0750)
- name: Find all directories recursively in rke2/data
  ansible.builtin.find:
    paths: "{{ rke2_data_dir }}/data"
    file_type: directory
  register: rke2_data_dirs
  tags: ["stig"]

- name: Apply 0750 to all rke2/ directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0750'
  loop: "{{ rke2_data_dirs.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  tags: ["stig"]

# 6. Verify correct permissions of all files in /var/lib/rancher/rke2/data (root:root, 0750)
- name: Find all files recursively in rke2/data
  ansible.builtin.find:
    paths: "{{ rke2_data_dir }}/data"
    file_type: file
    recurse: true
  register: rke2_data_files
  tags: ["stig"]

- name: Apply 750 to all rke2/data files
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0750'
  loop: "{{ rke2_data_files.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  tags: ["stig"]

# 7. Fix permissions in /var/lib/rancher/rke2/server (Server Only)
- name: Set root ownership on items directly inside server directory
  ansible.builtin.file:
    path: "{{ rke2_data_dir }}/server"
    owner: root
    group: root
  when: service_name == 'rke2-server'
  tags: ["stig"]

- name: Set 0700 on server cred, db, and tls directories
  ansible.builtin.file:
    path: "{{ rke2_data_dir }}/server/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0700'
  loop:
    - cred
    - db
    - tls
  when: service_name == 'rke2-server'
  failed_when: false
  loop_control:
    label: "{{ item }}"
  tags: ["stig"]

- name: Set 0750 on server manifests and logs directories
  ansible.builtin.file:
    path: "{{ rke2_data_dir }}/server/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0750'
  loop:
    - manifests
    - logs
  when: service_name == 'rke2-server'
  failed_when: false
  loop_control:
    label: "{{ item }}"
  tags: ["stig"]
